name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        cd fridge_chef_app
        npm install
        
    - name: Build
      run: |
        cd fridge_chef_app
        npm run build
        
    - name: Copy landing page and organize files
      run: |
        # Copy the built React app assets to a subdirectory (excluding index.html)
        mkdir -p ./fridge_chef_app_built
        cp -r fridge_chef_app/dist/assets ./fridge_chef_app_built/
        
        # Copy the landing page to root
        cp index.html ./
        
        # Copy other project files
        cp dcf_model.html ./
        cp fridge_chef_app.html ./
        cp server.py ./
        cp "control_flow_examples.py" ./
        cp "hello world.py" ./
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ 